title: Seitaro SHINAGAWA / 品川 政太朗
description: a Assistant Professor working on Vision and Language Communication Research
google_analytics: 
show_downloads: False
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions
