title: Seitaro SHINAGAWA / 品川 政太朗
description: a Ph.D student working on Dialogue-based Image Generation
google_analytics: 
show_downloads: False
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions
